name: Push Master

on:
  push:
    branches:
      - master

jobs:
  publish-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}'
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'
          scope: '@up42'
      - run: yarn install
      - run: yarn run publish:release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
          scope: '@up42'
      - run: yarn run publish:release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
