name: Release versions

on:
  push:
    branches:
      - master
      - next

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: action/chechkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          scope: '@up42'

      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}'
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Build app
        run: |
          yarn install
          yarn test

      - name: Publish version to GitHub Package Registry
        run: yarn run publish:gpr
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish version to NPM
        run: yarn run publish:npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
